server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=example-route

spring.cloud.gateway.routes[0].uri=https://httpbin.org

spring.cloud.gateway.routes[0].predicates[0]=Path=/example/**